# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='noofmem',
            field=models.IntegerField(default=0),
        ),
    ]
