# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_auto_20171027_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('FID', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.FloatField(default=0.0)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('HID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.House')),
            ],
        ),
        migrations.DeleteModel(
            name='Counties',
        ),
    ]
