# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_auto_20171027_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=2017)),
                ('paddypercent', models.FloatField()),
                ('wheatpercent', models.FloatField()),
                ('maizepercent', models.FloatField()),
                ('canepercent', models.FloatField()),
                ('spicespercent', models.FloatField()),
                ('oilseedspercent', models.FloatField()),
                ('otherspercent', models.FloatField()),
                ('FID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.Farm')),
            ],
        ),
        migrations.RemoveField(
            model_name='crops',
            name='FID',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='HID',
        ),
        migrations.DeleteModel(
            name='Yields',
        ),
        migrations.DeleteModel(
            name='Crops',
        ),
        migrations.DeleteModel(
            name='Farms',
        ),
    ]
