# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_auto_20171027_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='year',
            field=models.FloatField(max_length=2017),
        ),
        migrations.AlterField(
            model_name='house',
            name='noofmem',
            field=models.IntegerField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='household',
            name='Age',
            field=models.FloatField(default=0, max_length=150),
        ),
    ]
