# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_auto_20171027_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='noofmem',
            field=models.FloatField(default=0, max_length=30),
        ),
    ]
