# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0008_auto_20171027_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='FID',
            new_name='FarmID',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='FID',
            new_name='FarmID',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='geom',
            new_name='Geometry',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='HID',
            new_name='HouseID',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='HID',
            new_name='HouseID',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='HID',
            new_name='HouseID',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='PID',
            new_name='PersonID',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='FID',
            new_name='FarmID',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='WID',
            new_name='WellID',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='canepercent',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='maizepercent',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='oilseedspercent',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='otherspercent',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='paddypercent',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='spicespercent',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='wheatpercent',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='year',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='area',
        ),
        migrations.RemoveField(
            model_name='house',
            name='income',
        ),
        migrations.RemoveField(
            model_name='house',
            name='noofmem',
        ),
        migrations.RemoveField(
            model_name='well',
            name='avgwateryield',
        ),
        migrations.RemoveField(
            model_name='well',
            name='depth',
        ),
        migrations.AddField(
            model_name='crop',
            name='Maize',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='Oilseeds',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='Others',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='Paddy',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='Spices',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='Sugarcane',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='Wheat',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='Year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2017)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='Area',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='Income',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='NoOfMembers',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well',
            name='AverageWaterYield',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='well',
            name='Depth',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='household',
            name='Age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='household',
            name='Name',
            field=models.CharField(max_length=30),
        ),
    ]
