# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0009_auto_20171027_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Housephoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.FileField(blank=True, null=True, upload_to='')),
                ('HouseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.House')),
            ],
        ),
    ]
