# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_farmphoto_wellphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Houseaudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Audio', models.FileField(blank=True, null=True, upload_to='')),
                ('HouseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.House')),
            ],
        ),
    ]
